auth:
  rootPassword: poly1234
  username: poly
  password: poly1234
  database: myDB

primary:
  persistence:
    enabled: true
    size: 8Gi

  resources:
    limits:
      memory: 1Gi
      cpu: "1"
    requests:
      memory: 500Mi
      cpu: "500m"

  service:
    type: NodePort
    nodePorts:
      mysql: 30036 # 원하는 NodePort 번호를 설정합니다 (30000-32767 범위 내)
