
apiVersion: v1
kind: Secret
metadata:
  name: poly-secret
  namespace: kopo-trainee1
type: Opaque
data:
  username: cG9seQ==  # 'poly'를 base64로 인코딩한 값
  password: cG9seTEyMzQ=  # 'poly1234'를 base64로 인코딩한 값

